development:
  adapter: postgresql
  encoding: utf8
  database: garden_development
  pool: 5
test: &TEST
  adapter: postgresql
  encoding: utf8
  database: garden_test
  pool: 5

# production:
#   adapter: postgresql
#   encoding: utf8
#   database: garden_production
#   pool: 5


production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: garden_production
  username: garden
  password: <%= ENV['GARDEN_DATABASE_PASSWORD'] %>

# #
# DATABASE_URL="postgres://nqduiidbsljlli:3a11230953fb6a8eef6fe0e0e388f2443e75567f8a46d7da95c588e319f5a8d6@ec2-54-75-227-173.eu-west-1.compute.amazonaws.com:5432/d5mb66l83622el"
# #
# # You can use this database configuration with:
# #
# production:
#   url: <%= ENV['DATABASE_URL'] %>
# #

# # SQLite version 3.x
# #   gem install sqlite3
# #
# #   Ensure the SQLite 3 gem is defined in your Gemfile
# #   gem 'sqlite3'
# #
# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3

# # Warning: The database defined as "test" will be erased and
# # re-generated from your development database when you run "rake".
# # Do not set this db to the same as development or production.
# test:
#   <<: *default
#   database: db/test.sqlite3

# production:
#   <<: *default
#   database: db/production.sqlite3
